# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         List-SkipList
version:      0.33
version_from: lib/List/SkipList.pm
installdirs:  site
requires:
    Carp::Assert:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
