--- #YAML:1.0
name: List-SkipList
version: 0.40
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Perl implementation of skip lists
license: perl
requires:
  Carp::Assert: 0
  perl: 5.6.1
provides: {}
generated_by: Module::Build version 0.24
