--- #YAML:1.0
name: List-SkipList
version: 0.32
license: perl
distribution_type: module
requires:
  Carp::Assert: 0
  perl: 5.6.1
recommends: {}
build_requires: {}
conflicts: {}
provides:
  List::SkipList:
    file: lib/List/SkipList.pm
    version: 0.32
  List::SkipList::Node:
    file: lib/List/SkipList.pm
    version: 0.32
generated_by: Module::Build version 0.20
